blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    path('', PostLV.as_view(), name='index'),

    # /blog/post
    path('post/', PostLV.as_view(), name='post_list'),

    # /blog/post/{python-programming}
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    path('archive/', PostAV.as_view(), name='post_archive'),

    # Example: /2021/
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2021/01/
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2021/01/21/
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/ -> http://127.0.0.1:8000/blog/today/
    path('today/', PostTAV.as_view(), name='post_today_archive'),
]

bookmarkapp/urls.py
from django.conf.urls import url
from django.urls import path

from bookmarkapp.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

mybookmark/urls.py
from django.contrib import admin
from django.urls import path, include

from mybookmark.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),    
    # path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
    # 
    path('bookmark/', include('bookmarkapp.urls', namespace='bookmark')),
    path('blog/', include('blog.urls', namespace='blog')),  
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model): 
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for this alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        # ordering = ('modify_date','author')        # asc & author
        ordering = ('-modify_date',)        # desc, 
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,)) # -> 1st post -> /blog/post/1st-post

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

bookmarkapp/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView
from django.views.generic.dates import MonthArchiveView, DayArchiveView, TodayArchiveView
from blog.models import Post

# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = "posts" #object_list 
    
    paginate_by = 3

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = "modify_date"

class PostYAV(YearArchiveView):
    model = Post
    make_object_list = True
    date_field = "modify_date"

class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"
class PostDAV(DayArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"
class PostTAV(TodayArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"

bookmarkapp/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmarkapp.models import Bookmark
# from rest_framework.views import APIView
# from rest_framework.response import Response


class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

# class ApiBookmark(APIView):
#     def get(self, request):
#         return Response("ok", status=200)

mybookmark/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = "home.html"

blog/templates/blog/post_all.html
<h1>Blog List</h1>

<!-- display blog list -->
{% for post in posts%}
    <h2><a href="{% url 'blog:post_detail' post.slug %}">{{post.title}}</a></h2>
    {{post.modify_date|date:"Y-m-d H:i"}}
    <p>{{post.description}}</P>
{% endfor %}
<br/>

<!-- paging link -->
<div>
    
        
        {% if page_obj.has_previous%}
            <a href = "?page={{ page_obj.previous_page_number}}"> Prev</a>
        {% endif %}

        

    [    Page {{ page_obj.number}} / {{ page_obj.paginator.num_pages}}]

        {% if page_obj.has_next%}
            <a href = "?page={{ page_obj.next_page_number}}"> Next</a>
        {% endif %}
        
    
</div>

blog/templates/blog/post_archive.html
<h1>Post Archives until {% now "Y m d" %}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">{{date|date:'Y'}}</a>
        </li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
    {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
    {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_day.html
<h1>일변 등록된 게시물 {{ day|date:'Y-m-d' }}</h1>

<div>
    <ul>
    {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
    {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:'Y, N' }}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'m' date|date:'d'%}">{{date|date:'Y-m-d'}}</a>
        </li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
    {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
    {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{ year|date:'Y' }}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'m'%}">{{date|date:'b'}}</a>
        </li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
    {% for post in object_list %}
        <li>
            {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
    {% endfor %}
    </ul>
</div>

blog/templates/blog/post_detail.html
<h2></h2>

<!-- previous or next post link -->
<p class="other_posts">
    <a href = "{{ object.get_previous_post.get_absolute_url}}">
        {{object.get_previous_post}}
    </a>

    <a href = "{{ object.get_next_post.get_absolute_url}}">
        {{object.get_next_post}}
    </a>
</p>

<!-- date -->
<p class="date">
    {{object.modify_date|date:"Y"}}
</p>
<br/>
<!-- post content -->
<div class="body">
    {{ object.content | linebreaks}}
</div>
Hello <br>
Hello2

bookmarkapp/templates/bookmarkapp/bookmark_detail.html
<!DOCTYPE html>
<html>
<head>
<title>Django Bookmark Detail</title>
</head>
<body>
<div id="content">
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL: <a href='{{ object.url }}'>{{ object.url }}</a></li>
    </ul>
</div>
</body>
</html>

bookmarkapp/templates/bookmarkapp/bookmark_list.html
<!DOCTYPE html>
<html>
<head>
<title>Django Bookmark List</title>
</head>
<body>
<div id="content">
    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="ko">

    <head>
        <title>{% block title %}Django Web Programming{% endblock %}</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

    </head>

    <body>

        <div id="header">
            <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
            <h4 class="welcome">Welcome, <a href="#">OOO</a> /
                <a href="#">Change Password</a> /
                <a href="#">Logout</a>
            </h4>
        </div>

        <div id="menu">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="#">Photo</a></li>
            <li><a href="#">Add&bigtriangledown;</a>
                <ul>
                    <li><a href="#">Bookmark</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Photo</a></li>
                </ul>
            </li>
            <li><a href="#">Change&bigtriangledown;</a>
                <ul>
                    <li><a href="#">Bookmark</a></li>
                    <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
                </ul>
            </li>

            <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
            <li><a href="{% url 'blog:search' %}">Search</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
        </div>

        {% block content %}{% endblock %}

        {% block footer %}{% endblock %}

    </body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title%}home.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
    <div id="content_home">
        <div id="homeimg">
            <img src="{% static 'img/django-actor-big.jpg' %}" style="height: 400px;"/>
            <h4 style="margin: 0;">This is Django powered web site.</h4>
        </div>
    </div>

    {% comment %} <div style="margin-top: 100px;">
    <form action="[서버의 URL]" method="get">
        키워드 검색: <input type="text" name="search_word"> <br/>
        검색 범위: <input type="radio" name="category"> IT &nbsp;&nbsp;
                <input type="radio" name="category"> 여행
                <br>
        <input type="submit" value="검색">
    </form>
    </div> {% endcomment %}
{% endblock %}

{% block footer %}
    <div id="footer">
        &copy; This is FOOTER area.
    </div>
{% endblock %}